server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:mysql://localhost:3306/fastkill?serverTimezone=UTC&useUnicode=true&useSSL=false&characterEncoding=utf8
    url: jdbc:mysql://localhost:3306/fastkill?serverTimezone=UTC&useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: tiger
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
#  redis连接池
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
#    password: 123456
logging:
  pattern:
    console: "%d -%msg%n" #只显示日期和内容
    level: debug #指定日志级别